- name: netplan apply
  shell: echo -ne '\n' | netplan try
  register: netplan
  failed_when: netplan.rc != 0

- name: disable ondemand
  systemd: name=ondemand state=stopped enabled=false
  register: result_systemd_stop
  failed_when: "result_systemd_stop is failed and 'Could not find the requested service' not in result_systemd_stop.msg"

- name: restart cpufrequtils
  systemd: name=cpufrequtils state=restarted enabled=true

- name: update grub
  shell: /usr/sbin/update-grub
  register: grub
  failed_when: grub.rc != 0

- name: sync
  shell: sync

- name: reboot
  reboot:
    msg: 'Running reboot handler...'
    connect_timeout: 5
    reboot_timeout: 300
    test_command: 'echo Machine is started and ready'
