- name: update grub
  shell: /usr/sbin/update-grub

- name: disable ondemand
  systemd: name=ondemand state=stopped enabled=false

- name: restart cpufrequtils
  systemd: name=cpufrequtils state=restarted enabled=true

- name: netplan apply
  shell: echo -ne '\n' | netplan try

- name: sync
  shell: sync

- name: reboot
  reboot:
    msg: 'Running reboot handler...'
    connect_timeout: 5
    reboot_timeout: 300
    test_command: 'echo Machine is started and ready'
